name: pixiv_dart_api
description: Pixiv Dart API
version: 2.0.4
homepage: https://pixiv.xiaocao.moe/#/pixiv-api/dart
repository: https://github.com/git-xiaocao/pixiv_dart_api

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  dio: ^4.0.6
  json_annotation: ^4.5.0
  crypto: ^3.0.2
dev_dependencies:
  json_serializable: ^6.2.0
  build_runner: ^2.1.11